import "./globals.css";
import PrelineScript from "../components/PrelineScript";
import Navbar from "../components/Navbar";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Navbar />
				{children}
			</body>
			<PrelineScript />
		</html>
	);
}
